### PR TITLE
Cylinder3 PR

### PR DESCRIPTION
**Pull request by edljk**
Feel free to modify..

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thanks a lot! :) I was just about to comment to just open a PR!

**Comment by edljk** [comment]
A simple example (for sure not very efficient)

```julia
window = glscreen(); nbc = 300; rr = 3.
large_sphere = HyperSphere(Point3f0(0), 1f0)
positions = decompose(Point3f0,large_sphere); nbc = length(positions)
cc = Array{Cylinder3{Float32},1}(nbc)
for k = 1:nbc
  cc[k] = Cylinder3{Float32}(positions[k],positions[k]*rr,Float32(0.1))
  vis = visualize(GLNormalMesh(cc[k],80),color=RGBA{Float32}(rand(),rand(),rand()))
  _view(vis,window)
end
@async renderloop(window)
```

**Comment by SimonDanisch** [comment]
Let me know when you think this is ready to merge!
For a merge it would be nice to have some simple tests so that the coverage doesn't go down ;)

**Comment by SimonDanisch** [comment]
Is it not ready?

**Comment by edljk** [comment]
Not yet :-(. Soon I hope. Just want to have a 3D and 2D compatibility..

**Comment by SimonDanisch** [comment]
Okay! Well let me know, I was looking forward to this :)

**Pull request closed without merging**
