### PR TITLE
convert to testsets

### PR DESCRIPTION
**Pull request by jw3126**
It seems FactCheck is deprecated, so here is a PR to convert to TestSets.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Lovely! Thanks a lot. Let me figure out what the 0.6 failure is about before merging! ;)

**Comment by jw3126** [comment]
Sure! I also looked at it and it seems that you have the same 0.6 failure without this PR.

**Comment by SimonDanisch** [comment]
thanks again! :)

**Comment by jw3126** [comment]
No problem, I profited a lot from your packages in the past!

**Pull request merged**
