### PR TITLE
FlexibleSimplex, FlexibleConvexHull

### PR DESCRIPTION
**Pull request by jw3126**
Added a convex hull and simplex type whose number of points are mutable. See #60 .

### CODE REVIEW

**Comment by jw3126** [comment]
I added an implementation of the [gjk](https://en.wikipedia.org/wiki/Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm) algorithm, which allows to compute distances between various convex things. For example we can now compute distances between any combination of simpliex, hypercubes, convex hulls, hyperrectangels, vector. 
The gjk algorithm also has the nice feature, that it is very easily expendable to new geometries. The new geometry only needs to provide a "support" method, which is often a one liner.

What do you guys think, should that be part of the GeometryTypes package or better live elsewhere?

**Comment by SimonDanisch** [comment]
This looks great! :) I'll have a better look at it some time today. Is this ready to merge?

**Comment by jw3126** [comment]
Yeah its ready to merge.

**Comment by SimonDanisch** [comment]
Thanks! :)

**Pull request merged**
