### PR TITLE
fully upgrade to v0.6 syntax and remove Compat.jl

### PR DESCRIPTION
**Pull request by rdeits**
Sorry for the crazy number of PRs today. I've been busy 😉 and wanted to keep the various changes as small and discrete as possible. 

This removes all the compatibility clutter and fully upgrades to v0.6 syntax. It should prevent deprecation warnings on the v0.7 nightlies ~~(but the nightly tests will fail until #95 #97  comes in first).~~

### CODE REVIEW

**Comment by rdeits** [comment]
(rebased onto master)

**Comment by SimonDanisch** [comment]
Seems like a good idea, thanks! :)

**Comment by rdeits** [comment]
Ok, ready to merge? (I don't have merge permissions for this repo)

**Comment by SimonDanisch** [comment]
Ah you don't? Sorry I thought I gave you merge permissions...

**Pull request merged**
