### PR TITLE
add isinside function

### PR DESCRIPTION
**Pull request by mkborregaard**
We need the definition of AbstractPoint, but not sure how you want to play that with how it's implemented here. And Polygons should specify that the Points are 2D.
Also needed - interface methods, tests, and a way to ensure that e.g. HyperRectangles{2} can also be treated as polygons.
Or - can 3D mesh triangles be polygons too? (probably not, but spatial data e.g. can have this duality - they are flat polygons on a space (the earth) which is distended along the third dimension. probably best to just ignore the 3rd dimension though in that case?)

### CODE REVIEW

**Comment by mkborregaard** [comment]
@sjkelly oh wow I'd forgotten about this PR. If your implementation is better, then by all means. Are they similar performance-wise?

**Comment by sjkelly** [comment]
I am not sure about the performance. It may be good to run some benchmarks. The paper is pretty bold in their claims, so it would be good to verify. It will probably be a little while before I finish up the clipping algorithm component. I am working over at: https://github.com/JuliaGeometry/PolygonOps.jl for now because these algorithms can be pretty generic (across e.g. GeometryTypes, GeometryBasics, GIS).

**Comment by mkborregaard** [comment]
@SimonDanisch Is this so stale that it would be better to reimplement from scratch? Should we just go with @sjkelly  's instead and close?

**Comment by sjkelly** [comment]
I am unopposed to merging once conflicts are resolved. FWIW I implemented both the Hao Sun and Hormann Agathos algorithms in [PolygonOps](https://github.com/JuliaGeometry/PolygonOps.jl). It is untagged, but if you would prefer to test that package to see if it works for you, I can tag.

**Comment by mkborregaard** [comment]
@SimonDanisch thanks for merging this.
So - I just realized that there are no tests here. Where would you like me to add them - just one of the toy polygons here? https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/test/polygons.jl

**Comment by SimonDanisch** [comment]
That would be awesome :)

**Pull request merged**
