### PR TITLE
[RFC] initial sketch of Polytope/Polygon/Polyhedron type

### PR DESCRIPTION
**Pull request by sjkelly**
Hopefully this will be useful for representing polygons and polyhdra. I see it more useful for combinatoric Polyhdra, since HomogenousMesh adequately covers most of what we would want with Polygon meshes. The hope is that this will allow nice conversion between Polygon types represented as a collection of line segments, or as a collection of points. I will be writing some algorithms to test this design out.

### CODE REVIEW

**Comment by yeesian** [comment]
:+1:

**Comment by yeesian** [comment]
I'm not sure if it applies, but I'll be working on a wrapper for OGR geometries at some point, and it'll be nice if there can be some sort of mapping from [their class hierarchy](http://www.gdal.org/classOGRGeometry.html) to some of the types here. See https://github.com/JuliaGeometry/GeometryTypes.jl/issues/3.

**Comment by yeesian** [comment]
Also, a few questions:

1. Is it based on the definition of a [complex polygon](http://math.stackexchange.com/questions/784048/what-is-inside-and-outside-of-complex-polygon), where the edges are allowed to intersect each other?
2. Is it going to support "holes" (and have "inner" versus "outer" geometries), e.g. for the representation of a donut?

**Comment by sjkelly** [comment]
@yeesian thanks for sharing the OGR class hierarchy. I think adding a curve type will be a good exercise for `Polytope`.

>1. Is it based on the definition of a [complex polygon](http://math.stackexchange.com/questions/784048/what-is-inside-and-outside-of-complex-polygon), where the edges are allowed to intersect each other?

I think this should be added. So we can have `ComplexPolytopes <:AbstractPolytope` that self-intersect. I think we should then name `Polytope` to `SimplePolytope`.

> 2. Is it going to support "holes" (and have "outer" versus "inner" geometries), e.g. for the representation of a donut (which [can be rendered in Cairo, SVG and Patchwork](https://github.com/dcjones/Compose.jl/commit/0d517df354d5cf02c4d700ed9e0dac69ee4c1f9c))?

The idea would be to represent holes as clock-wise oriented polygons, and outer perimeters as CCW oriented. The works well for functional representations and offsetting for example. Maybe we should create a type that can represent this composition of polygons. Generally I've found an array of polygons to be adequate, but it seems that OGR provides such a type. This could be useful for dispatch.

**Comment by yeesian** [comment]
> Generally I've found an array of polygons to be adequate

How should a `Vector{Vector{Point}}` be understood then?

---

It seems hard to distinguish between

1. a single polygon (with holes)
2. a collection of polygons (with or without holes) and lines

The distinction might be important, because if you were to define e.g.

```julia
in(g1::Point, g2::Vector{Vector{Point}})
```

It might return `Bool` if `g2` is a single polygon, and `Vector{Bool}` if `g2` is a collection of polygons.

---

And it matters in the verification of the validity of the geometries/polygons: whether or not you enforce the checking of their validity (e.g. "orientation", "holes" should be contained in their exterior "shell", etc) during their construction, versus in each geometric operation.

**Comment by sjkelly** [comment]
I think the best approach here will be apparent once we add wrappers for CSG operations. I do agree that the ambiguities in `in` methods will be confusing quickly. Generally for complex polygons you need to set a 'fill' convention, since it isn't just based on winding order like a simple polygon. I think the easiest thing to do for this release is add `Polytope` (assumed to be simple), and `ComplexPolytope` (may be self-incident). 

I have plans to bring in geometric set operation wrapper types for composing functional representations and BSPs. The current iteration lives in Descartes https://github.com/FactoryOS/Descartes.jl/blob/71c6aa56c92a223d87c7867ed06327e6cc99c44b/src/types.jl#L41-L63, but quickly taxes inference with the type parameterization. Until this happens it will be best to refrain from defining any geometry conventions over Vectors of objects.

**Comment by blegat** [comment]
About the Polyhedron type: there is a terminology conflict between Geometry and other fields such as optimization and algebraic topology (see [here](http://mathworld.wolfram.com/Polyhedron.html)).
In Geometry a polyhedron is a 3D polytope but in the other fields it is an intersection of half spaces. It is called a polytope when it is bounded. I have built a [package](https://github.com/blegat/Polyhedra.jl) to manipulate polyhedra and the type of polyhedra is `Polyhedron{N,T}` (which is a subtype of `GeometryPrimitive{N,T}`). This type may conflict with your type of the same name :/

**Comment by yeesian** [comment]
> I think the easiest thing to do for this release is add Polytope (assumed to be simple), and ComplexPolytope (may be self-incident). [...] it will be best to refrain from defining any geometry conventions over Vectors of objects.

Sorry I haven't followed this in a while, but that sounds like the best way to proceed. Thanks for pushing hard on this!

**Comment by SimonDanisch** [comment]
I can't really comment on this, since it's a bit far away from my use cases... I'd go with anything you come up to resolve this ;)

**Pull request closed without merging**
