### PR TITLE
Try to improve efficency of cylinders

### PR DESCRIPTION
**Pull request by edljk**
Comments welcome!
In particular I am not sure of the most efficient/clean way to apply rotation
````julia
vertices[position] = PT(M*Point{3,T}(c.r*cos(phi),c.r*sin(phi),0))+PT(c.origin)
````
in decompose.jl

### CODE REVIEW

**Comment by SimonDanisch** [comment]
If you want to use StaticArrays, you should base this PR on sd/staticarrays
```Julia
vertices[position] = PT(M*Point{3,T}(c.r*cos(phi),c.r*sin(phi),0))+PT(c.origin)
```
Looks fine! What problems do you have with it?

**Comment by edljk** [comment]
My matrix product produce a static array which is not of type PT. I wonder if the conversion is costly..
By the way, it would be perhaps simpler that I wait you merge  sd/staticarrays and then  propose a compatible version ?

**Comment by SimonDanisch** [comment]
You can just branch of sd/staticarrays.
The conversion should be a no-op on the low level!

**Comment by edljk** [comment]
OK I can try to do that :-)..
Btw, after git checkout origin/sd/staticarrays and then loading GeometryTypes gives me

````julia
julia> using GeometryTypes
INFO: Precompiling module GeometryTypes.
ERROR: LoadError: LoadError: too many parameters for type typealias
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading $HOME/.julia/v0.5/GeometryTypes/src/types.jl, in expression starting on line 480
while loading $HOME/.julia/v0.5/GeometryTypes/src/GeometryTypes.jl, in expression starting on line 40
ERROR: Failed to precompile GeometryTypes to $HOME/.julia/lib/v0.5/GeometryTypes.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
```
...

**Comment by SimonDanisch** [comment]
Ah, you need to checkout master of StaticArrays!

**Comment by SimonDanisch** [comment]
What was the state of this?

**Comment by edljk** [comment]
Replaced by a [more recent PR](https://github.com/JuliaGeometry/GeometryTypes.jl/pull/120) ..

**Pull request closed without merging**
