### PR TITLE
fixes for GLVisualize

### PR DESCRIPTION
**Pull request by SimonDanisch**
This fixes a few problems I had when working on GLVisualize.
One was, that decompose sometimes returns tuples, which isn't working well when you want to upload an array to the GPU ;) Would be awkward to special case that situation...@sjkelly, why did we ditch `Vector{Point}(geometry)` in favor of `decompose(Point, geometry)` ?  This would nicely solve the problem, if you want an `Array` or `NTuple`... I only remember that I was in the mood of `whatever you do is fine by me`  :D 
For now I just changed `decompose(Point, ::HyperRectangle)` to return an array. Hope it's okay with you as a temporary solution. Speed suffers, but at least decompose now returns the same type!

I think most changes should be fine, but I would like to make one pass over it, comment stuff and remove some lazy/inconsistent hacks!

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Whoops... guess I haven't run the tests for some time :D 
Also,  I introduced `isdecomposable`, since `isapplicable` wouldn't work because of our catchall decompose method.... But I need to know if something is decomposable to correctly build up the meshtype.
E.g. `isdecomposable(Normal, geom)` might be `false`, but I can still get normals by calculating them from the faces!

**Comment by SimonDanisch** [comment]
Also, I added the resolution argument for decomposing SimpleRectangle... We could include this into the API, to have more control over the granularity of the generated mesh (like it's already the case for Sphere)...

**Comment by sjkelly** [comment]
Cursory inspection, this looks really good! The tuple<=>array relation is really a problem right now on 0.4, but from what I can tell the appropriate mechanisms are in 0.5. The idea behind the tuple and array ambiguity was whether the decomposition was of deterministic length (this might be in a docstring).

**Comment by sjkelly** [comment]
Also, needs tests! :) I think we should be shooting for coverage improvements at this point too.

**Comment by SimonDanisch** [comment]
Yup! true story...

**Comment by SimonDanisch** [comment]
huh... so what's `origin` supposed to be?
In `HyperCube` it's the minimum and for `HyperSphere`, it's the center... The latter seems to be more true to the meaning? But then the fieldname for HyperCube would be confusing....

**Comment by SimonDanisch** [comment]
85% :)

**Comment by sjkelly** [comment]
I don't even think the mathematicians have that one figured out :p. The
name is less important to me than the consistency across types. This is
pretty uniform to me since a HyperSphere is more the bounded euclidean
norm, while a HyperCube is the cross product of orthogonal equal length
intervals. Geometrically the word "origin" is confusing, but mathematically
it seems okay to me.

**Comment by SimonDanisch** [comment]
I guess this means no objections? So I'm going to merge this :)

**Pull request merged**
