### PR TITLE
Fix slice to use the correct offset

### PR DESCRIPTION
**Pull request by dreammaker**
I was getting a `BoundsError` without this.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I think this would best be:
```Julia
v1,v2,v3 = mesh.vertices[face]
```

**Comment by dreammaker** [comment]
I don't understand what you mean.  `mesh.vertices` is a Vector so the code you wrote won't function.  ...unless there's already code that allows `getindex()` of a face that I don't know about.

**Comment by SimonDanisch** [comment]
Yeah that's exactly the case ;) It takes care of the offset and such.
We really need some documentation!

**Comment by dreammaker** [comment]
@SimonDanisch, I updated this pull request.

**Comment by sjkelly** [comment]
Sweet. I didn't know about the getindex trick.

**Pull request merged**
