### PR TITLE
create constructors instead of convert methods for OffsetInteger

### PR DESCRIPTION
**Pull request by rdeits**
Fixes a few more deprecation warnings on Julia v0.7. I also raised the minimum Julia version to v0.7-alpha to avoid accidentally breaking 0.6.

### CODE REVIEW

**Comment by rdeits** [comment]
I also added some more tests to try to make sure we don't have any OffsetInteger bugs.

**Comment by SimonDanisch** [comment]
Awesome! Do we actually need to bump the require, though?

**Comment by rdeits** [comment]
Possibly not. I can try leaving it as is and see if everything still passes on 0.6.

**Comment by SimonDanisch** [comment]
Ah ok, it fails on 0.6 for me... No worries, I don't want you to waste work on it then. Let's just merge!

**Comment by rdeits** [comment]
done!

**Pull request merged**
