### PR TITLE
add support for sorting OffsetIntegers

### PR DESCRIPTION
**Pull request by jonalm**
Fixing #180

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thank you! Would be super nice if you could add one simple test for this :)

**Comment by jonalm** [comment]
Like this? The test fails on master now.

**Comment by SimonDanisch** [comment]
You mean Julia master? CI looks like it works so far?

**Comment by SimonDanisch** [comment]
```
(v1.4) pkg> add https://github.com/jonalm/GeometryTypes.jl#support_sorting_offsetinteger
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `https://github.com/jonalm/GeometryTypes.jl`
  Updating git-repo `https://github.com/jonalm/GeometryTypes.jl`
  Updating git-repo `https://github.com/jonalm/GeometryTypes.jl`
 Resolving package versions...
  Updating `~/.julia/environments/v1.4/Project.toml`
  [4d00f742] + GeometryTypes v0.7.5 #support_sorting_offsetinteger (https://github.com/jonalm/GeometryTypes.jl)
  Updating `~/.julia/environments/v1.4/Manifest.toml`
  [3da002f7] + ColorTypes v0.8.0
  [53c48c17] + FixedPointNumbers v0.6.1
  [4d00f742] + GeometryTypes v0.7.5 #support_sorting_offsetinteger (https://github.com/jonalm/GeometryTypes.jl)
  [c8e1da08] + IterTools v1.2.0
  [90137ffa] + StaticArrays v0.11.0
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [9a3f8284] + Random 
  [9e88b42a] + Serialization 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 

(v1.4) pkg> test GeometryTypes
   Testing GeometryTypes
 Resolving package versions...
    Status `/tmp/jl_5NSNra/Manifest.toml`
  [3da002f7] ColorTypes v0.8.0
  [53c48c17] FixedPointNumbers v0.6.1
  [4d00f742] GeometryTypes v0.7.5 #support_sorting_offsetinteger (https://github.com/jonalm/GeometryTypes.jl)
  [c8e1da08] IterTools v1.2.0
  [90137ffa] StaticArrays v0.11.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]

Test Summary: | Pass  Total
GeometryTypes |  401    401
   Testing GeometryTypes tests passed 

```

**Comment by SimonDanisch** [comment]
Thanks, looks good to me! Are there any concerns left?

**Comment by jonalm** [comment]
No concerns. I was just pointing out that I had checked that the test crashed on the repo master, which it obviously should :)

**Pull request merged**
